### ISSUE TITLE
Holograms not showing & a lot of errors

### ISSUE THREAD

**Issue by larssieboy18** [hornta/racing#22]
Hi,

I am using the Racing plugin (v. 1.14.1) and holograms are not shown. I have a feeling it is related to the error spam I get in console. I have put some in Pastebin (https://pastebin.com/WcYcMAAp), if you need any more logs, let me know. 

I really like the plugin and it would be a shame if the errors persisted.

Best regards,
Lars

**Comment by hornta** [comment]
Are you using the correct version of ProtocolLib?

**Comment by larssieboy18** [comment]
Hi,

I’m using ProtocoLib for version 1.14. All other plugins (like HD Extension) work fine, only racing is producing errors. I’m using Paper v. 1.14.4 btw

**Comment by hornta** [comment]
Ok, that is another error you've posted and I believe I know the cause. Would you mind send your config.yml?
Can you try an delete your config.yml and then start the server? If that doesn't work. Try starting the server with an existing config.yml

**Comment by larssieboy18** [comment]
Hi,
This is my config: https://pastebin.com/2Thbjw0G

I will try to restart my server without a config, lets see what happens.

**Comment by larssieboy18** [comment]
EDIT: default config still gives errors, see: https://pastebin.com/32qiFVmp

**Comment by hornta** [comment]
I fixed the bug in version 1.14.2 of Racing. Let me know if it works for you and I can close this.

**Comment by larssieboy18** [comment]
Hi,

The errors are gone, all holograms work. Thanks for that! However, the commands at start still don't work, as we just started a race and still had just 3 food left.

**Comment by hornta** [comment]
All players will be put to 3 hunger during the countdown phase and when it ends and the race starts all players will receive full hunger
